# Generated by Django 2.1.11 on 2020-04-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_ticket', models.CharField(max_length=50)),
                ('date_out', models.DateField(null=True)),
                ('date_in', models.DateField(null=True)),
                ('borrower', models.CharField(max_length=50)),
                ('technician', models.CharField(max_length=50)),
                ('adapter_included', models.BooleanField(default=True)),
                ('checked_in', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('hard_drive', models.CharField(max_length=50)),
                ('screen', models.CharField(max_length=50)),
                ('vendor', models.PositiveSmallIntegerField(choices=[(1, 'Dell'), (2, 'Lenovo')])),
            ],
        ),
        migrations.AddField(
            model_name='loaner',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaners.Model'),
        ),
    ]
