# Generated by Django 2.1.11 on 2020-04-10 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('borrower', models.CharField(max_length=50)),
                ('technician', models.CharField(max_length=50)),
                ('action_date', models.DateField(null=True)),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaners.Loaner')),
            ],
        ),
    ]
