# Generated by Django 2.1.11 on 2020-05-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaners', '0003_record_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='action_date',
            field=models.DateTimeField(null=True),
        ),
    ]
