# Generated by Django 2.1.11 on 2020-05-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaners', '0004_auto_20200506_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaner',
            name='date_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='loaner',
            name='date_out',
            field=models.DateTimeField(null=True),
        ),
    ]
