# Generated by Django 2.1.11 on 2020-05-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaners', '0005_auto_20200506_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaner',
            name='service_ticket',
        ),
    ]
